vim.pack.add({
    "https://github.com/Mofiqul/vscode.nvim",
    "https://github.com/nvim-tree/nvim-web-devicons",
    "https://github.com/nvim-lualine/lualine.nvim",
    "https://github.com/linrongbin16/lsp-progress.nvim",
    "https://github.com/akinsho/bufferline.nvim",
    "https://github.com/goolord/alpha-nvim",
    "https://github.com/akinsho/toggleterm.nvim",
    "https://github.com/mistweaverco/kulala.nvim",
    "https://github.com/nvim-tree/nvim-tree.lua",
    "https://github.com/saghen/blink.cmp",
    "https://github.com/mfussenegger/nvim-dap",
    "https://github.com/nvim-treesitter/nvim-treesitter",
    "https://github.com/neovim/nvim-lspconfig",
    "https://github.com/williamboman/mason.nvim",
    "https://github.com/williamboman/mason-lspconfig.nvim",
    "https://github.com/nvim-telescope/telescope.nvim",
    "https://github.com/nvim-lua/plenary.nvim",
    "https://github.com/MagicDuck/grug-far.nvim",
})

require("init-options")
require("init-plugins")
require("init-keymap")
require("init-lsp")
