hl.bind("XF86PowerOff", hl.dsp.exec_cmd("loginctl lock-session && sleep 1 && systemctl suspend"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume increase"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume decrease"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume muteOutput"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume muteInput"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness increase"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness decrease"))

hl.bind("SUPER                      + DELETE", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("SUPER                      + BACKSLASH", hl.dsp.dpms({ action = "toggle", monitor = "current" }))
hl.bind("SUPER                      + T", hl.dsp.exec_cmd("ghostty"))
hl.bind("SUPER                      + X", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))
hl.bind("SUPER                      + B", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER                      + PRINT", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))
hl.bind("SUPER              + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))

hl.bind("SUPER + ALT + CTRL + SHIFT + DELETE", hl.dsp.exit())
hl.bind("SUPER                      + V", hl.dsp.layout("togglesplit"))
hl.bind("SUPER              + SHIFT + C", hl.dsp.window.kill({ window = "activewindow" }))
hl.bind("SUPER                      + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER                      + F", hl.dsp.window.fullscreen({ action = "toggle" }))

hl.bind("SUPER                      + H", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER                      + L", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER                      + K", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER                      + J", hl.dsp.focus({ direction = "d" }))
hl.bind("SUPER                      + LEFT ", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER                      + RIGHT", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER                      + UP   ", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER                      + DOWN ", hl.dsp.focus({ direction = "d" }))
hl.bind("SUPER              + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER              + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER              + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER              + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER              + SHIFT + LEFT ", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER              + SHIFT + RIGHT", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER              + SHIFT + UP   ", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER              + SHIFT + DOWN ", hl.dsp.window.move({ direction = "d" }))

hl.bind("SUPER                      + COMMA", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER                      + PERIOD", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER              + SHIFT + COMMA", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER              + SHIFT + PERIOD", hl.dsp.window.move({ workspace = "e+1" }))

hl.bind("SUPER                      + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER                      + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER                      + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER                      + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER                      + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER                      + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER                      + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER                      + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER                      + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER                      + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER                      + m", hl.dsp.focus({ workspace = 666 }))

hl.bind("SUPER              + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER              + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER              + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER              + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER              + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER              + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER              + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER              + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER              + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER              + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind("SUPER              + SHIFT + m", hl.dsp.window.move({ workspace = 666 }))

hl.bind("SUPER                      + GRAVE", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER              + SHIFT + GRAVE", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind("SUPER                      + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER                      + mouse:273", hl.dsp.window.resize(), { mouse = true })
